In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\HP\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 5.0 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.9 MB 3.0 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.9 MB 3.1 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.9 MB 3.1 MB/s eta 0:00:03
   -------------- ------------------------- 3.7/9.9 MB 3.6 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.9 MB 4.1 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.9 MB 4.4 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.6 MB/s  0:00:02
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [6]:
data = {'Name':['Alice','Bob'],'Age':[25,30]}

In [7]:
df = pd.DataFrame(data)

In [8]:
lst = [['Alice',25],['Bob',30]]

In [9]:
df = pd.DataFrame(lst,columns=['Name','Age'])

In [10]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [11]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [13]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [14]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [15]:
df[['Name','Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [16]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [17]:
df.loc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [18]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [19]:
df['Gender'] = ['F','M']

In [20]:
df.drop('Age',axis=1,inplace=True)

In [21]:
df.isnull()

    Name  Gender
0  False   False
1  False   False

In [22]:
df.dropna()

    Name Gender
0  Alice      F
1    Bob      M

In [23]:
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [35]:
df['Age']=[25,30]

In [36]:
df.groupby('Gender')['Age'].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [40]:
df1 = pd.DataFrame({
    'key' : [1,2,3],
    'Name' : ['Alice','Bob','Charlie']
})
df2 = pd.DataFrame({
    'key' : [1,2,3],
    'Age' : [20,21,22]
})

In [41]:
pd.merge(df1,df2,on='key')

   key     Name  Age
0    1    Alice   20
1    2      Bob   21
2    3  Charlie   22

In [43]:
df1.join(df2, lsuffix='_left', rsuffix='_right')

   key_left     Name  key_right  Age
0         1    Alice          1   20
1         2      Bob          2   21
2         3  Charlie          3   22

In [51]:
df = pd.read_csv("C:/Users/HP/OneDrive/文件/datass.csv")

In [52]:
df.to_csv('output.csv',index=False)

In [53]:
df.sort_values('Age')

      Name  Age Gender
0    Alice   20      f
1      Bob   26      m
2  Charlie   27      m

In [54]:
df['Age'].apply(lambda x:x+1)

0    21
1    27
2    28
Name: Age, dtype: int64

In [55]:
df['Name'].unique()

<StringArray>
['Alice', 'Bob', 'Charlie']
Length: 3, dtype: str

In [56]:
df['Age'].value_counts()

Age
20    1
26    1
27    1
Name: count, dtype: int64